version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: project-php
    working_dir: /var/www/html/backend
    volumes:
      - ./backend:/var/www/html/backend
      - ~/.composer/cache:/root/.composer/cache
    networks:
      - app-network

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: project-node
    working_dir: /var/www/html/frontend
    volumes:
      - ./frontend:/var/www/html/frontend
    ports:
      - "5173:5173"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: project-nginx
    depends_on:
      - php
      - node
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/var/www/html/frontend
      - ./backend/public:/var/www/html/backend/public
    ports:
      - "80:80"
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: project-db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
